name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0 
    - name: Helm Chart Releaser
      # You may pin to the exact commit or the version.
      # uses: helm/chart-releaser-action@565e7795cebb33bb2cf4f52ab8f779e21b9fa262
      uses: helm/chart-releaser-action@v1.1.0      
      env:
        CR_TOKEN: "${{ secrets.GH_TOKEN }}"